# fly.toml app configuration file generated for movie-polls on 2024-02-01T14:47:23-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movie-polls'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
